### ISSUE TITLE
speed of read_nonmem / FORMAT=,... 

### ISSUE THREAD

**Issue by ronkeizer** [dpastoor/PKPDmisc#18] opened 2015-03-18 19:34 UTC
hi Devin,

I've briefly compared PKPDmisc::read_nonmem vs vpc::read_table_nm. For default output tables from NONMEM it is indeed faster than vpc::read_table_nm, compared to either the Perl-fallback or the even slower readLines approach in vpc::read_tables_nm. I see about a 2-3x increase in speed compared to the Perl preprocessing approach. 

However, I've noticed that when the table is created in NONMEM using comma as separator (e.g. using  FORMAT=,1PE11.4 like we recommend as "tip" in vpc::read_table_nm):
- PKPDmisc::read_nonmem is about 2x slower than vpc::read_table_nm
- the data is not read correctly

Perhaps you should try first to read using fread(), like done in vpc::read_table_nm, and only fallback to the cpp implementation if that fails?

**Comment by dpastoor** [comment] 2015-03-18 20:10
actually can do one better and properly implement a tokenizer. Essentially, right now, I'm replacing the white space with commas before passing it along to read_csv. All it takes is me pulling in say 2-3 lines, checking what the most likely delimiter is (at minimum yes/no for commas) then passing through.

This way it would also be easy to handle any kind of separator reasonably robustly. 

The other problem with the fread implementation currently, is there isn't a fast way of stripping out the table/column headings, so it needs extra massaging if you have sim data vs just a regular table.

**Comment by dpastoor** [comment] 2015-03-18 21:03
ok should be fixed with d38449da19edd1dfc703a334dfdb965ea8a5c7b4 - it is not a complete solution yet (as in it won't handle any possible type of separator), but it will now handle both comma separated and space separated nonmem outputs with the same speed. 

I also bumped the version so people can check with devtools::session_info() and should have at least PKPDmisc v0.3.0.2 to guarantee read_nonmem will handle both file separators.

**Comment by dpastoor** [comment] 2015-03-18 21:06
going to close for now, but feel free to reopen if you notice any other bugs.

**Comment by dpastoor** [comment] 2015-03-18 21:08
oh and for future reference, I'm guessing the random speed drop (even though it read in successfully) was since the behavior was to replace whitespace with ',', there must have been multiple commas per true separator, which bogged down the parser trying to figure out what to do. It should now be faster no matter what.

**Comment by ronkeizer** [comment] 2015-03-18 21:49
The new implementation works, and is faster than before. But for a comma-separated dataset, the PKPDmisc::read_nonmem was still (slightly) slower than vpc::read_table_nm(), 6.1 vs 4.8 seconds

The head of that dataset looks like this (I can share full dataset too, just let me know):

 ID         ,TIME       ,DV         ,CENS       ,EVID       ,AUC24      ,CMAX       ,DV         ,PRED       ,RES        ,WRES
  1.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 3.0000E+00, 7.8288E+01, 8.1970E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00
  1.0000E+00, 1.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 7.8288E+01, 8.1970E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00
  1.0000E+00, 2.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 7.8288E+01, 8.1970E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00
  1.0000E+00, 3.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 7.8288E+01, 8.1970E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00
  1.0000E+00, 4.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 7.8288E+01, 8.1970E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00
  1.0000E+00, 5.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 7.8288E+01, 8.1970E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00
  1.0000E+00, 6.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 7.8288E+01, 8.1970E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00
  1.0000E+00, 7.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 7.8288E+01, 8.1970E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00
  1.0000E+00, 8.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 7.8288E+01, 8.1970E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00

Additionally, I now get this warning message (for either tab-separated or comma-separated):

Warning message:
In read_tokens(ds, tokenizer, col_types, col_names, n_max = n_max,  :
  At [964601, 1]: expected a double, got 'NA'

**Comment by dpastoor** [comment] 2015-03-18 22:12
ah you mean when you're really using fread - I thought you meant the perl implementation was faster. Yes, the fread version will always be faster (even by hadley's admission). 

That is the next step, similar to what you mentioned above, is to use fread for the specific types of tables that fread will handle nicely (like comma separated values with no intermediate table/column names - so just big tables), but to go to the custom parser + readr stream when need to actually properly handle parsing.

As of now, really the 'only' time someone can use fread (at least from my tests) is with single rep tables, which in the majority of cases are small enough that it is an imperceptible difference of milliseconds. 

That said, the options are:

1) have an fread argument that someone can call if they want max speed and are confident that their table is appropriately formed - the value is you 'always' use `read_nonmem()` 

2) give either a message or well document that there is a faster implementation `read_table()` that is faster than `read_nonmem()` but won't parse NSUB tables 

3) mess around with a way of scanning the lines, checking if is comma separated and no table statements, etc, and if true then fread, and if false do the full parsing. I don't know how much time those checks would take though.

I'd lean towards 1 or 2. Your thoughts?

**Comment by dpastoor** [comment] 2015-03-18 22:13
To the warning message, this might be due to a missing value in nonmem. I think I set the default incorrectly to ".", when it might actually need to be "\." to not escape the period.

**Comment by dpastoor** [comment] 2015-03-18 22:17
hmm nope nevermind - the "." works fine as an NA value - I think if you can zip and shoot me the full dataset I would have an easier time tracking it down. Looks like it is at the very end of the dataset (or near it)

**Comment by ronkeizer** [comment] 2015-03-18 22:51
> As of now, really the 'only' time someone can use fread...

I don't think this is true. If you use NOTITLE and FORMAT=,.... in $TABLE and repeat simulations, it's perfectly fine to use fread(). That's actually what I was using to test read_nonmem(). 

Regarding the options, I think arguments or messages should be a last resort. Sure, one could that the difference between fread and read_nonmem is not so big, but it's still about 20% in my (limited) tests. 
So I still see the solution we have in vpc::read_table_nm as a better one than the options above. I.e. try fread() first, and if it fails fallback to something else (read_nonmem()). This will then require no user input and will parse anything, either superfast (using fread) or near-superfast (using read_nonmem). The thing is though that you should make sure that fread fails fast. You can do that by specifying nrow=3 or something to fread(). I'm updating my vpc::read_table_nm() to do that too, I saw it currently tries to read in the whole file.

**Comment by dpastoor** [comment] 2015-03-18 23:11
Ah, but you still get the rows with column names (that turn into a row of pure NA's I believe) so it's not exactly the most elegant. How do you handle that (barring of course just filtering those rows out)

The situation we were trying to avoid previously that you had rightly brought up, is we want to make this reasonable enough for the 'default' user to use most of the time (eg not having to constantly be specifying NOTITLE, FORMAT...) 

For example, with your fread implementation that only scans 3 lines, if they didn't include NOTITLE, it would pass the initial scan, try fread, fail after it actually tried to read in the whole file (since it didn't detect the misaligned `table` rows, then drop down to perl/scan.

Also, regarding failing fast, the problem is the biggest reason for fread to fail is the misc. table statements spread throughout, not the format of the data (esp if comma separated).  fread by default only checks in the first, middle, and last ~30 lines to determine the appropriate parser and column types anyway, so it will fail out then anyway - it doesn't try to read in the whole thing then fail. 

I actually have a more general version of the read_table_nm() - `read_table()` that will also handle phoenix data with units and leverages fread. 

One other option is similar to your FORMAT message, is to give a FYI message where if scanning and not detecting title lines, to notify user, if they need more performance that the dataset would likely be capable of using read_table/... 

My thought is if the person is 'knowledgeable/informed' enough to be whipping out NOTITLE/FORMAT... then they shouldn't be bothered by adding one extra argument passed (fread=T) OR just all-together use read_table/read_table_nm() if they are confident of their output.

**Comment by ronkeizer** [comment] 2015-03-19 00:34
> Ah, but you still get the rows with column names (that turn into a row of pure NA's I believe) so it's not exactly the most elegant. How do you handle that (barring of course just filtering those rows out)

Well, in my view "elegance" is primarily important in the context of user experience and speed, secondly in how it is implemented in the code. As in principle it's faster than read_nonmem() and it relieves the user of specifying argument names or messages, I htink fread should be used if possible.

However you are right regarding the case when users do not specify NOTITLE and do multiple sims, for that you can't use fread. If there is no better way to test if fread will fail or not for those cases, then I agree the next best option is to use read_nonmem() by default and have fread=TRUE as argument for "power users". I'm not a big fan of showing a warning messages / tip for a small improvement in performance. They should read the manual :)

**Comment by dpastoor** [comment] 2015-03-19 00:54
amen to that - I tried around ways of testing fread and just can't come up with a way that still keeps the performance of fread (eg you essentially have to scan the lines to check for those table statements), which for bigger files, say 120 MB, is ~ 1 second of read time, which negates most any gain data.table gives since you can both scan the lines with c++ using readr::read_lines(), which is what read_nonmem() already does, so by that point just keep passing it into the clean_nonmem c++ function under the hood.

I definitely agree that just a good clear vignette (or two) should hopefully make it abundantly clear that read_nonmem() is the fastest general parser we can reasonably expect without trying to microoptimize, and that if they truly need speed or have really large files, then use the format/notitle/no... options to make it fread friendly.

**Comment by dpastoor** [comment] 2015-03-28 18:20
closing for now

**Closed by dpastoor** 2015-03-28 18:20 UTC
